spring:
  application:
    name: sem8
  cloud:
    config:
      fail-fast: true
      uri: http://localhost:8888
      label: main
  config:
    import: optional:configserver:http://localhost:8888
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,metrics


