version: '3.1'

services:
      mysql_db:
            image: mysql:latest
            restart: always
            ports:
                  - "33006:3306"
            environment:
                  MYSQL_ROOT_PASSWORD: secret
                  MYSQL_DATABASE: testDb
                  MYSQL_USER: example
                  MYSQL_PASSWORD: secret2
            volumes:
                  - ./mysql-db:/var/lib/mysql/